_target_: src.models.lit_module.OCRLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 8.317637711026709e-05
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 3
  threshold: 1e-4
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1e-8
  verbose: True

tokenizer:
  _target_: src.models.tokenizer.Tokenizer

net:
  _target_: src.models.model.Net

  backbone:
    _target_: src.models.components.cnn.CNN
    model:
      _target_: src.models.components.vgg.Vgg
      weights: IMAGENET1K_V1
      # pooling stride size
      ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
      # pooling kernel size
      ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
      # dim of ouput feature map
      hidden: 256
      dropout: 0.5

  transformer:
    _target_: src.models.components.transformer.Transformer
    tokenizer:
      _target_: src.models.tokenizer.Tokenizer

    d_model: 256
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 2048
    max_seq_length: 512
    pos_dropout: 0.2
    trans_dropout: 0.1
